name: release
on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  cd:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: build and pack
        run: |
          npm i
          npm run compile
          npx vsce package --no-dependencies

      - name: get package version
        id: package-version
        run: |
          echo "version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT

      - name: upload to release page
        uses: ncipollo/release-action@v1.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.package-version.outputs.version }}
          artifacts: ./*.vsix
          commit: ${{ github.sha }}